source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Set ruby version via ENV
send :ruby, ENV['GEMFILE_RUBY_VERSION'] if ENV['GEMFILE_RUBY_VERSION']

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.1'

# Authentication and Authorization
gem 'doorkeeper', '~> 5.4'
gem 'devise', '~> 4.7'
gem 'devise_invitable', '~> 2.0.0'
gem 'pundit'

# Use postgresql as the database for Active Record
gem 'pg', '~> 1.2'

# Use Puma as the app server
gem 'puma', '~> 5'

# Rack Middlwares
gem 'rack-cors'
gem 'rack-attack'

# Use Redis adapter
gem 'redis', '~> 4.1.0'
gem 'hiredis', "~> 0.6"

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# JSON API
gem 'jsonapi-serializer', '~> 2.1'

# SassC-Ruby with Rails!
gem 'sassc-rails'

# Rails engine for static pages.
gem 'high_voltage', '~> 3.1'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'rspec-rails', '~> 4'
  gem 'factory_bot_rails', '~> 5.0'
  gem 'ffaker'
  gem 'jsonapi-rspec'
end

group :development do
  gem 'annotate'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'database_cleaner'
  gem 'shoulda-matchers', '~> 4.1'
  gem 'simplecov', require: false
end

group :production do
  # TODO
end
